### ISSUE TITLE
Conflict with Magic Storage mod

### ISSUE THREAD

**Issue by c0ldk453** [dougbenham/Terraria-DougCustom#1]
Transcend's Customizations mod will cause Magic Storage mod to fail to load as of v2022.5.103.32 - Magic Storage has reportedly been updated for this issue.  Below is a log of the error thrown.

[12:27:25] [.NET ThreadPool Worker/ERROR] [tML]: An error occurred while loading MagicStorage v0.5.5.2
It has been detected that this mod was built for tModLoader v2022.5.103.30
However, you are using tModLoader v2022.5.103.32
The mod(s) have been automatically disabled.
System.AggregateException: One or more errors occurred. (The given key '4' was not present in the dictionary.)
 ---> System.Collections.Generic.KeyNotFoundException: The given key '4' was not present in the dictionary.
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at TranscendCustom.Item.SetUseTime(Item item) in TranscendCustom\Item.cs:line 40
   at Terraria.ModLoader.ItemLoader.SetDefaults(Item item, Boolean createModItem) in tModLoader\Terraria\ModLoader\ItemLoader.cs:line 172
   at Terraria.Item.SetDefaults(Int32 Type, Boolean noMatCheck) in tModLoader\Terraria\Item.cs:line 45176
   at Terraria.Item..ctor(Int32 setDefaultsToType, Int32 stack, Int32 prefix) in tModLoader\Terraria\Item.cs:line 215
   at MagicStorage.Sorting.SortingCacheDictionary.<>c.<Create>b__4_0(Int32 i) in MagicStorage\Sorting\SortingCache.cs:line 49
   at System.Linq.Parallel.SelectQueryOperator`2.SelectQueryOperatorEnumerator`1.MoveNext(TOutput& currentElement, TKey& currentKey)
   at System.Linq.Parallel.SortQueryOperatorEnumerator`3.MoveNext(TInputOutput& currentElement, TSortKey& currentKey)
   at System.Linq.Parallel.SortHelper`2.BuildKeysFromSource(GrowingArray`1& keys, List`1& values)
   at System.Linq.Parallel.SortHelper`2.Sort()
   at System.Linq.Parallel.OrderPreservingSpoolingTask`2.SpoolingWork()
   at System.Linq.Parallel.SpoolingTaskBase.Work()
   at System.Linq.Parallel.QueryTask.BaseWork(Object unused)
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
   --- End of inner exception stack trace ---
   at System.Linq.Parallel.QueryTaskGroupState.QueryEnd(Boolean userInitiatedDispose)
   at System.Linq.Parallel.OrderPreservingSpoolingTask`2.Spool(QueryTaskGroupState groupState, PartitionedStream`2 partitions, Shared`1 results, TaskScheduler taskScheduler)
   at System.Linq.Parallel.OrderPreservingMergeHelper`2.System.Linq.Parallel.IMergeHelper<TInputOutput>.Execute()
   at System.Linq.Parallel.MergeExecutor`1.Execute()
   at System.Linq.Parallel.MergeExecutor`1.Execute[TKey](PartitionedStream`2 partitions, Boolean ignoreOutput, ParallelMergeOptions options, TaskScheduler taskScheduler, Boolean isOrdered, CancellationState cancellationState, Int32 queryId)
   at System.Linq.Parallel.PartitionedStreamMerger`1.Receive[TKey](PartitionedStream`2 partitionedStream)
   at System.Linq.Parallel.SortQueryOperatorResults`2.ChildResultsRecipient.Receive[TKey](PartitionedStream`2 childPartitionedStream)
   at System.Linq.Parallel.UnaryQueryOperator`2.UnaryQueryOperatorResults.ChildResultsRecipient.Receive[TKey](PartitionedStream`2 inputStream)
   at System.Linq.Parallel.ScanQueryOperator`1.ScanEnumerableQueryOperatorResults.GivePartitionedStream(IPartitionedStreamRecipient`1 recipient)
   at System.Linq.Parallel.UnaryQueryOperator`2.UnaryQueryOperatorResults.GivePartitionedStream(IPartitionedStreamRecipient`1 recipient)
   at System.Linq.Parallel.SortQueryOperatorResults`2.GivePartitionedStream(IPartitionedStreamRecipient`1 recipient)
   at System.Linq.Parallel.QueryOperator`1.GetOpenedEnumerator(Nullable`1 mergeOptions, Boolean suppressOrder, Boolean forEffect, QuerySettings querySettings)
   at System.Linq.Parallel.QueryOpeningEnumerator`1.OpenQuery()
   at System.Linq.Parallel.QueryOpeningEnumerator`1.MoveNext()
   at System.Linq.ParallelEnumerable.ToList[TSource](ParallelQuery`1 source)
   at MagicStorage.Sorting.SortingCacheDictionary.Create(SortMode mode) in MagicStorage\Sorting\SortingCache.cs:line 47
   at MagicStorage.Sorting.SortingCacheDictionary.Fill() in MagicStorage\Sorting\SortingCache.cs:line 35
   at Terraria.ModLoader.SystemLoader.PostSetupContent(Mod mod) in tModLoader\Terraria\ModLoader\SystemLoader.cs:line 75
   at Terraria.ModLoader.ModContent.<>c.<Load>b__41_1(Mod mod) in tModLoader\Terraria\ModLoader\ModContent.cs:line 325
   at Terraria.ModLoader.ModContent.LoadModContent(CancellationToken token, Action`1 loadAction) in tModLoader\Terraria\ModLoader\ModContent.cs:line 369
   at Terraria.ModLoader.ModContent.Load(CancellationToken token) in tModLoader\Terraria\ModLoader\ModContent.cs:line 321
   at Terraria.ModLoader.ModLoader.Load(CancellationToken token) in tModLoader\Terraria\ModLoader\ModLoader.cs:line 122

**Comment by dougbenham** [comment]
Thanks for the bug report! Will solve it soon!

**Comment by dougbenham** [comment]
Fixed!
